define({
  root: ({
    businessAnalyst: "Business Analyst",
    defineWhichInfographics: "Define which infographics are available in the widget:",
    defineWhichReports: "Define which reports are available in the widget:",
    defaultValues: "Default values:",
    disable: "Disable",
    driveTime: "Drive time",
    infographics: "Infographics",
    km: "km",
    miles: "miles",
    minutes: "minutes",
    radius: "Radius",
    reports: "Reports",
    rings: "Rings",
    selectCountry: "Select country:",
    time: "Time",
    walkTime: "Walk time"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lv": 0,
  "lt": 0,
  "nl": 0,
  "nb": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0,
  "zh-hk": 0,
  "zh-tw": 0
});
