define({
  root: {
      trackedEvents: "Tracked Map Events",
      trackedLayers: "Tracked Layers",
      logClk: "Log Map Clicks",
      logDblClk: "Log Map Double Clicks",
      logExtChg: "Log Map Extent Changes",
      logPan: "Log Map Pans",
      logZoom: "Log Map Zoom",  
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": false
});