define({
  root: ({
    _widgetLabel: "Business Analyst",
    addPoint: "Add point by clicking on the map",
    addRingsDtWt: "Add rings, drive time or walk time.",
    apply: "Apply",
    back: "Back",
    colon: ":",
    creditInformation: "Credit Information",
    driveTime: "Drive time",
    esriInfographics: "Esri Infographics",
    esriReports: "Esri Reports",
    headerDescription_km: "kilometer",
    headerDescription_miles: "mile",
    headerDescription_minutes: "minute",
    infographics: "Infographics",
    km: "km",
    miles: "miles",
    minutes: "minutes",
    myInfographics: "My Infographics",
    myReports: "My Reports",
    noPermissions: "Your account cannot run the Business Analyst widget.  In order to run the Business Analyst widget, the administrator of your organization needs to grant you GeoEnrichment and Network Analysis <a href=\"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm\" target=\"_blank\">privileges</a>, and also allocate <a href=\"https://doc.arcgis.com/en/arcgis-online/administer/configure-credits.htm?\" target=\"_blank\">credits</a>.",
    radii: "radii",
    radius: "Radius",
    radius_lowercase: "radius",
    reports: "Reports",
    ring: "Ring",
    rings: "Rings",
    runInfographic: "Run Infographic",
    runReport: "Run Report",
    selectPointOrPolygon: "Select a Point or Polygon feature on the map, search for an address or place, or drop a pin on the map to view more information for areas.",
    selectReport: "Select Report",
    selectTemplate: "Select Template",
    sharedInfographics: "Shared Infographics",
    sharedReports: "Shared Reports",
    time: "Time",
    walkTime: "Walk time",
    widgetDescription: "Access Infographics and Reports that summarize key indicators and data for any area.",

    // Filtering Select
    None: "Select..."
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lv": 0,
  "lt": 0,
  "nl": 0,
  "nb": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0,
  "zh-hk": 0,
  "zh-tw": 0
});
